# MongoDB Connection (Using Environment Variables)
spring.data.mongodb.uri=${MONGODB_URI}

spring.application.name=school-payment
server.port=8080

# Paystack Key (Using Environment Variables)
paystack.secret.key=${PAYSTACK_SECRET_KEY}