
spring.data.mongodb.uri=mongodb://localhost:27017/school_payments
spring.application.name=school-payment
server.port=8080

# Use environment variables so keys are never hardcoded in GitHub
paystack.secret.key=${PAYSTACK_SECRET_KEY}